//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ffmpeg.ffprobe700;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ffmpeg.ffprobe700 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Ffprobe_QNAME = new QName("http://www.ffmpeg.org/schema/ffprobe", "ffprobe");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ffmpeg.ffprobe700
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FfprobeType }
     * 
     * @return
     *     the new instance of {@link FfprobeType }
     */
    public FfprobeType createFfprobeType() {
        return new FfprobeType();
    }

    /**
     * Create an instance of {@link PacketsType }
     * 
     * @return
     *     the new instance of {@link PacketsType }
     */
    public PacketsType createPacketsType() {
        return new PacketsType();
    }

    /**
     * Create an instance of {@link FramesType }
     * 
     * @return
     *     the new instance of {@link FramesType }
     */
    public FramesType createFramesType() {
        return new FramesType();
    }

    /**
     * Create an instance of {@link PacketsAndFramesType }
     * 
     * @return
     *     the new instance of {@link PacketsAndFramesType }
     */
    public PacketsAndFramesType createPacketsAndFramesType() {
        return new PacketsAndFramesType();
    }

    /**
     * Create an instance of {@link TagsType }
     * 
     * @return
     *     the new instance of {@link TagsType }
     */
    public TagsType createTagsType() {
        return new TagsType();
    }

    /**
     * Create an instance of {@link PacketType }
     * 
     * @return
     *     the new instance of {@link PacketType }
     */
    public PacketType createPacketType() {
        return new PacketType();
    }

    /**
     * Create an instance of {@link PacketSideDataListType }
     * 
     * @return
     *     the new instance of {@link PacketSideDataListType }
     */
    public PacketSideDataListType createPacketSideDataListType() {
        return new PacketSideDataListType();
    }

    /**
     * Create an instance of {@link PacketSideDataType }
     * 
     * @return
     *     the new instance of {@link PacketSideDataType }
     */
    public PacketSideDataType createPacketSideDataType() {
        return new PacketSideDataType();
    }

    /**
     * Create an instance of {@link PacketSideDatumType }
     * 
     * @return
     *     the new instance of {@link PacketSideDatumType }
     */
    public PacketSideDatumType createPacketSideDatumType() {
        return new PacketSideDatumType();
    }

    /**
     * Create an instance of {@link FrameType }
     * 
     * @return
     *     the new instance of {@link FrameType }
     */
    public FrameType createFrameType() {
        return new FrameType();
    }

    /**
     * Create an instance of {@link LogsType }
     * 
     * @return
     *     the new instance of {@link LogsType }
     */
    public LogsType createLogsType() {
        return new LogsType();
    }

    /**
     * Create an instance of {@link LogType }
     * 
     * @return
     *     the new instance of {@link LogType }
     */
    public LogType createLogType() {
        return new LogType();
    }

    /**
     * Create an instance of {@link FrameSideDataListType }
     * 
     * @return
     *     the new instance of {@link FrameSideDataListType }
     */
    public FrameSideDataListType createFrameSideDataListType() {
        return new FrameSideDataListType();
    }

    /**
     * Create an instance of {@link FrameSideDataType }
     * 
     * @return
     *     the new instance of {@link FrameSideDataType }
     */
    public FrameSideDataType createFrameSideDataType() {
        return new FrameSideDataType();
    }

    /**
     * Create an instance of {@link FrameSideDatumType }
     * 
     * @return
     *     the new instance of {@link FrameSideDatumType }
     */
    public FrameSideDatumType createFrameSideDatumType() {
        return new FrameSideDatumType();
    }

    /**
     * Create an instance of {@link FrameSideDataTimecodeList }
     * 
     * @return
     *     the new instance of {@link FrameSideDataTimecodeList }
     */
    public FrameSideDataTimecodeList createFrameSideDataTimecodeList() {
        return new FrameSideDataTimecodeList();
    }

    /**
     * Create an instance of {@link FrameSideDataTimecodeType }
     * 
     * @return
     *     the new instance of {@link FrameSideDataTimecodeType }
     */
    public FrameSideDataTimecodeType createFrameSideDataTimecodeType() {
        return new FrameSideDataTimecodeType();
    }

    /**
     * Create an instance of {@link FrameSideDataComponentList }
     * 
     * @return
     *     the new instance of {@link FrameSideDataComponentList }
     */
    public FrameSideDataComponentList createFrameSideDataComponentList() {
        return new FrameSideDataComponentList();
    }

    /**
     * Create an instance of {@link FrameSideDataComponentType }
     * 
     * @return
     *     the new instance of {@link FrameSideDataComponentType }
     */
    public FrameSideDataComponentType createFrameSideDataComponentType() {
        return new FrameSideDataComponentType();
    }

    /**
     * Create an instance of {@link FrameSideDataPieceList }
     * 
     * @return
     *     the new instance of {@link FrameSideDataPieceList }
     */
    public FrameSideDataPieceList createFrameSideDataPieceList() {
        return new FrameSideDataPieceList();
    }

    /**
     * Create an instance of {@link FrameSideDataPieceType }
     * 
     * @return
     *     the new instance of {@link FrameSideDataPieceType }
     */
    public FrameSideDataPieceType createFrameSideDataPieceType() {
        return new FrameSideDataPieceType();
    }

    /**
     * Create an instance of {@link SubtitleType }
     * 
     * @return
     *     the new instance of {@link SubtitleType }
     */
    public SubtitleType createSubtitleType() {
        return new SubtitleType();
    }

    /**
     * Create an instance of {@link StreamsType }
     * 
     * @return
     *     the new instance of {@link StreamsType }
     */
    public StreamsType createStreamsType() {
        return new StreamsType();
    }

    /**
     * Create an instance of {@link ProgramsType }
     * 
     * @return
     *     the new instance of {@link ProgramsType }
     */
    public ProgramsType createProgramsType() {
        return new ProgramsType();
    }

    /**
     * Create an instance of {@link StreamGroupsType }
     * 
     * @return
     *     the new instance of {@link StreamGroupsType }
     */
    public StreamGroupsType createStreamGroupsType() {
        return new StreamGroupsType();
    }

    /**
     * Create an instance of {@link StreamDispositionType }
     * 
     * @return
     *     the new instance of {@link StreamDispositionType }
     */
    public StreamDispositionType createStreamDispositionType() {
        return new StreamDispositionType();
    }

    /**
     * Create an instance of {@link StreamType }
     * 
     * @return
     *     the new instance of {@link StreamType }
     */
    public StreamType createStreamType() {
        return new StreamType();
    }

    /**
     * Create an instance of {@link ProgramType }
     * 
     * @return
     *     the new instance of {@link ProgramType }
     */
    public ProgramType createProgramType() {
        return new ProgramType();
    }

    /**
     * Create an instance of {@link StreamGroupType }
     * 
     * @return
     *     the new instance of {@link StreamGroupType }
     */
    public StreamGroupType createStreamGroupType() {
        return new StreamGroupType();
    }

    /**
     * Create an instance of {@link StreamGroupComponentList }
     * 
     * @return
     *     the new instance of {@link StreamGroupComponentList }
     */
    public StreamGroupComponentList createStreamGroupComponentList() {
        return new StreamGroupComponentList();
    }

    /**
     * Create an instance of {@link StreamGroupComponentType }
     * 
     * @return
     *     the new instance of {@link StreamGroupComponentType }
     */
    public StreamGroupComponentType createStreamGroupComponentType() {
        return new StreamGroupComponentType();
    }

    /**
     * Create an instance of {@link StreamGroupSubComponentList }
     * 
     * @return
     *     the new instance of {@link StreamGroupSubComponentList }
     */
    public StreamGroupSubComponentList createStreamGroupSubComponentList() {
        return new StreamGroupSubComponentList();
    }

    /**
     * Create an instance of {@link StreamGroupSubComponentType }
     * 
     * @return
     *     the new instance of {@link StreamGroupSubComponentType }
     */
    public StreamGroupSubComponentType createStreamGroupSubComponentType() {
        return new StreamGroupSubComponentType();
    }

    /**
     * Create an instance of {@link StreamGroupPieceList }
     * 
     * @return
     *     the new instance of {@link StreamGroupPieceList }
     */
    public StreamGroupPieceList createStreamGroupPieceList() {
        return new StreamGroupPieceList();
    }

    /**
     * Create an instance of {@link StreamGroupPieceType }
     * 
     * @return
     *     the new instance of {@link StreamGroupPieceType }
     */
    public StreamGroupPieceType createStreamGroupPieceType() {
        return new StreamGroupPieceType();
    }

    /**
     * Create an instance of {@link StreamGroupSubPieceList }
     * 
     * @return
     *     the new instance of {@link StreamGroupSubPieceList }
     */
    public StreamGroupSubPieceList createStreamGroupSubPieceList() {
        return new StreamGroupSubPieceList();
    }

    /**
     * Create an instance of {@link StreamGroupSubPieceType }
     * 
     * @return
     *     the new instance of {@link StreamGroupSubPieceType }
     */
    public StreamGroupSubPieceType createStreamGroupSubPieceType() {
        return new StreamGroupSubPieceType();
    }

    /**
     * Create an instance of {@link StreamGroupBlockList }
     * 
     * @return
     *     the new instance of {@link StreamGroupBlockList }
     */
    public StreamGroupBlockList createStreamGroupBlockList() {
        return new StreamGroupBlockList();
    }

    /**
     * Create an instance of {@link StreamGroupBlockType }
     * 
     * @return
     *     the new instance of {@link StreamGroupBlockType }
     */
    public StreamGroupBlockType createStreamGroupBlockType() {
        return new StreamGroupBlockType();
    }

    /**
     * Create an instance of {@link StreamGroupEntryType }
     * 
     * @return
     *     the new instance of {@link StreamGroupEntryType }
     */
    public StreamGroupEntryType createStreamGroupEntryType() {
        return new StreamGroupEntryType();
    }

    /**
     * Create an instance of {@link FormatType }
     * 
     * @return
     *     the new instance of {@link FormatType }
     */
    public FormatType createFormatType() {
        return new FormatType();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     * @return
     *     the new instance of {@link TagType }
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     * @return
     *     the new instance of {@link ErrorType }
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ProgramVersionType }
     * 
     * @return
     *     the new instance of {@link ProgramVersionType }
     */
    public ProgramVersionType createProgramVersionType() {
        return new ProgramVersionType();
    }

    /**
     * Create an instance of {@link ChaptersType }
     * 
     * @return
     *     the new instance of {@link ChaptersType }
     */
    public ChaptersType createChaptersType() {
        return new ChaptersType();
    }

    /**
     * Create an instance of {@link ChapterType }
     * 
     * @return
     *     the new instance of {@link ChapterType }
     */
    public ChapterType createChapterType() {
        return new ChapterType();
    }

    /**
     * Create an instance of {@link LibraryVersionType }
     * 
     * @return
     *     the new instance of {@link LibraryVersionType }
     */
    public LibraryVersionType createLibraryVersionType() {
        return new LibraryVersionType();
    }

    /**
     * Create an instance of {@link LibraryVersionsType }
     * 
     * @return
     *     the new instance of {@link LibraryVersionsType }
     */
    public LibraryVersionsType createLibraryVersionsType() {
        return new LibraryVersionsType();
    }

    /**
     * Create an instance of {@link PixelFormatFlagsType }
     * 
     * @return
     *     the new instance of {@link PixelFormatFlagsType }
     */
    public PixelFormatFlagsType createPixelFormatFlagsType() {
        return new PixelFormatFlagsType();
    }

    /**
     * Create an instance of {@link PixelFormatComponentType }
     * 
     * @return
     *     the new instance of {@link PixelFormatComponentType }
     */
    public PixelFormatComponentType createPixelFormatComponentType() {
        return new PixelFormatComponentType();
    }

    /**
     * Create an instance of {@link PixelFormatComponentsType }
     * 
     * @return
     *     the new instance of {@link PixelFormatComponentsType }
     */
    public PixelFormatComponentsType createPixelFormatComponentsType() {
        return new PixelFormatComponentsType();
    }

    /**
     * Create an instance of {@link PixelFormatType }
     * 
     * @return
     *     the new instance of {@link PixelFormatType }
     */
    public PixelFormatType createPixelFormatType() {
        return new PixelFormatType();
    }

    /**
     * Create an instance of {@link PixelFormatsType }
     * 
     * @return
     *     the new instance of {@link PixelFormatsType }
     */
    public PixelFormatsType createPixelFormatsType() {
        return new PixelFormatsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FfprobeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FfprobeType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ffmpeg.org/schema/ffprobe", name = "ffprobe")
    public JAXBElement<FfprobeType> createFfprobe(FfprobeType value) {
        return new JAXBElement<>(_Ffprobe_QNAME, FfprobeType.class, null, value);
    }

}
