//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.17 at 09:30:15 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ffmpeg.org/schema/ffprobe")
package org.ffmpeg.ffprobe700;
