//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ffmpeg.ffprobe700;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for streamGroupComponentType complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="streamGroupComponentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="subcomponents" type="{http://www.ffmpeg.org/schema/ffprobe}streamGroupSubComponentList" minOccurs="0"/&gt;
 *         &lt;element name="component_entry" type="{http://www.ffmpeg.org/schema/ffprobe}streamGroupEntryType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "streamGroupComponentType", propOrder = {
    "subcomponents",
    "componentEntry"
})
public class StreamGroupComponentType {

    protected StreamGroupSubComponentList subcomponents;
    @XmlElement(name = "component_entry")
    protected List<StreamGroupEntryType> componentEntry;

    /**
     * Gets the value of the subcomponents property.
     * 
     * @return
     *     possible object is
     *     {@link StreamGroupSubComponentList }
     *     
     */
    public StreamGroupSubComponentList getSubcomponents() {
        return subcomponents;
    }

    /**
     * Sets the value of the subcomponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamGroupSubComponentList }
     *     
     */
    public void setSubcomponents(StreamGroupSubComponentList value) {
        this.subcomponents = value;
    }

    /**
     * Gets the value of the componentEntry property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the componentEntry property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getComponentEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StreamGroupEntryType }
     * </p>
     * 
     * 
     * @return
     *     The value of the componentEntry property.
     */
    public List<StreamGroupEntryType> getComponentEntry() {
        if (componentEntry == null) {
            componentEntry = new ArrayList<>();
        }
        return this.componentEntry;
    }

}
