//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.17 at 09:30:15 PM CEST 
//


package org.ffmpeg.ffprobe700;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for streamGroupSubPieceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="streamGroupSubPieceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="blocks" type="{http://www.ffmpeg.org/schema/ffprobe}streamGroupBlockList" minOccurs="0"/&gt;
 *         &lt;element name="subpiece_entry" type="{http://www.ffmpeg.org/schema/ffprobe}streamGroupEntryType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "streamGroupSubPieceType", propOrder = {
    "blocks",
    "subpieceEntry"
})
public class StreamGroupSubPieceType {

    protected StreamGroupBlockList blocks;
    @XmlElement(name = "subpiece_entry")
    protected List<StreamGroupEntryType> subpieceEntry;

    /**
     * Gets the value of the blocks property.
     * 
     * @return
     *     possible object is
     *     {@link StreamGroupBlockList }
     *     
     */
    public StreamGroupBlockList getBlocks() {
        return blocks;
    }

    /**
     * Sets the value of the blocks property.
     * 
     * @param value
     *     allowed object is
     *     {@link StreamGroupBlockList }
     *     
     */
    public void setBlocks(StreamGroupBlockList value) {
        this.blocks = value;
    }

    /**
     * Gets the value of the subpieceEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subpieceEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubpieceEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StreamGroupEntryType }
     * 
     * 
     */
    public List<StreamGroupEntryType> getSubpieceEntry() {
        if (subpieceEntry == null) {
            subpieceEntry = new ArrayList<StreamGroupEntryType>();
        }
        return this.subpieceEntry;
    }

}
