//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.26 at 11:29:23 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ffmpeg.org/schema/ffprobe")
package org.ffmpeg.ffprobe810;
