//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.31 at 03:48:01 PM CET 
//


package org.ffmpeg.ffprobe436;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ffmpeg.ffprobe436 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Ffprobe_QNAME = new QName("http://www.ffmpeg.org/schema/ffprobe", "ffprobe");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ffmpeg.ffprobe436
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FfprobeType }
     * 
     */
    public FfprobeType createFfprobeType() {
        return new FfprobeType();
    }

    /**
     * Create an instance of {@link PacketsType }
     * 
     */
    public PacketsType createPacketsType() {
        return new PacketsType();
    }

    /**
     * Create an instance of {@link FramesType }
     * 
     */
    public FramesType createFramesType() {
        return new FramesType();
    }

    /**
     * Create an instance of {@link PacketsAndFramesType }
     * 
     */
    public PacketsAndFramesType createPacketsAndFramesType() {
        return new PacketsAndFramesType();
    }

    /**
     * Create an instance of {@link PacketType }
     * 
     */
    public PacketType createPacketType() {
        return new PacketType();
    }

    /**
     * Create an instance of {@link PacketSideDataListType }
     * 
     */
    public PacketSideDataListType createPacketSideDataListType() {
        return new PacketSideDataListType();
    }

    /**
     * Create an instance of {@link PacketSideDataType }
     * 
     */
    public PacketSideDataType createPacketSideDataType() {
        return new PacketSideDataType();
    }

    /**
     * Create an instance of {@link FrameType }
     * 
     */
    public FrameType createFrameType() {
        return new FrameType();
    }

    /**
     * Create an instance of {@link LogsType }
     * 
     */
    public LogsType createLogsType() {
        return new LogsType();
    }

    /**
     * Create an instance of {@link LogType }
     * 
     */
    public LogType createLogType() {
        return new LogType();
    }

    /**
     * Create an instance of {@link FrameSideDataListType }
     * 
     */
    public FrameSideDataListType createFrameSideDataListType() {
        return new FrameSideDataListType();
    }

    /**
     * Create an instance of {@link FrameSideDataType }
     * 
     */
    public FrameSideDataType createFrameSideDataType() {
        return new FrameSideDataType();
    }

    /**
     * Create an instance of {@link FrameSideDataTimecodeList }
     * 
     */
    public FrameSideDataTimecodeList createFrameSideDataTimecodeList() {
        return new FrameSideDataTimecodeList();
    }

    /**
     * Create an instance of {@link FrameSideDataTimecodeType }
     * 
     */
    public FrameSideDataTimecodeType createFrameSideDataTimecodeType() {
        return new FrameSideDataTimecodeType();
    }

    /**
     * Create an instance of {@link SubtitleType }
     * 
     */
    public SubtitleType createSubtitleType() {
        return new SubtitleType();
    }

    /**
     * Create an instance of {@link StreamsType }
     * 
     */
    public StreamsType createStreamsType() {
        return new StreamsType();
    }

    /**
     * Create an instance of {@link ProgramsType }
     * 
     */
    public ProgramsType createProgramsType() {
        return new ProgramsType();
    }

    /**
     * Create an instance of {@link StreamDispositionType }
     * 
     */
    public StreamDispositionType createStreamDispositionType() {
        return new StreamDispositionType();
    }

    /**
     * Create an instance of {@link StreamType }
     * 
     */
    public StreamType createStreamType() {
        return new StreamType();
    }

    /**
     * Create an instance of {@link ProgramType }
     * 
     */
    public ProgramType createProgramType() {
        return new ProgramType();
    }

    /**
     * Create an instance of {@link FormatType }
     * 
     */
    public FormatType createFormatType() {
        return new FormatType();
    }

    /**
     * Create an instance of {@link TagType }
     * 
     */
    public TagType createTagType() {
        return new TagType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link ProgramVersionType }
     * 
     */
    public ProgramVersionType createProgramVersionType() {
        return new ProgramVersionType();
    }

    /**
     * Create an instance of {@link ChaptersType }
     * 
     */
    public ChaptersType createChaptersType() {
        return new ChaptersType();
    }

    /**
     * Create an instance of {@link ChapterType }
     * 
     */
    public ChapterType createChapterType() {
        return new ChapterType();
    }

    /**
     * Create an instance of {@link LibraryVersionType }
     * 
     */
    public LibraryVersionType createLibraryVersionType() {
        return new LibraryVersionType();
    }

    /**
     * Create an instance of {@link LibraryVersionsType }
     * 
     */
    public LibraryVersionsType createLibraryVersionsType() {
        return new LibraryVersionsType();
    }

    /**
     * Create an instance of {@link PixelFormatFlagsType }
     * 
     */
    public PixelFormatFlagsType createPixelFormatFlagsType() {
        return new PixelFormatFlagsType();
    }

    /**
     * Create an instance of {@link PixelFormatComponentType }
     * 
     */
    public PixelFormatComponentType createPixelFormatComponentType() {
        return new PixelFormatComponentType();
    }

    /**
     * Create an instance of {@link PixelFormatComponentsType }
     * 
     */
    public PixelFormatComponentsType createPixelFormatComponentsType() {
        return new PixelFormatComponentsType();
    }

    /**
     * Create an instance of {@link PixelFormatType }
     * 
     */
    public PixelFormatType createPixelFormatType() {
        return new PixelFormatType();
    }

    /**
     * Create an instance of {@link PixelFormatsType }
     * 
     */
    public PixelFormatsType createPixelFormatsType() {
        return new PixelFormatsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FfprobeType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FfprobeType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.ffmpeg.org/schema/ffprobe", name = "ffprobe")
    public JAXBElement<FfprobeType> createFfprobe(FfprobeType value) {
        return new JAXBElement<FfprobeType>(_Ffprobe_QNAME, FfprobeType.class, null, value);
    }

}
