# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Unshallow git
      run: git fetch --unshallow
    - name: Update repos
      run: sudo apt-get update
    - name: Install ffmpeg
      run: sudo apt-get install -y ffmpeg
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: >-
        mvn -B package test verify
        -Dgpg.skip=true
        -Dmaven.javadoc.skip=true
        -Dmaven.source.skip=true
        -Pcoverage,sonar
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=hdsdi3g
        -Dsonar.projectKey=hdsdi3g_medialib
        -Dsonar.java.coveragePlugin=jacoco
        -Dsonar.dynamicAnalysis=reuseReports
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-aggregate/jacoco.xml
        --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

